language: python
python:
- '3.7'
script:
- nose2 -v
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: refaelkohen
  password:
    secure: wOnHmQazcIYhJe3rLhUgFHHqTUlkQaAFT/Njnypd3Uuk/fmOGNQ9jzE7JbtwV+vfXKvTGedfJzCO8Ykfp1nQCHgrOinOcGEcNvHe1x/Qvch85ZqxKj9yo5fDPsmmTpjhQbmlbQeV3F+mxGaS0QEqAgsUUG97rbgCbh95lvfWBem0h59JU4Wg109X4mj29D09veLwjJ3MYazxbUlpAilMLR0gQfKwt6e8arXa6l1VdqhypNiT+kibqa5r61XlTwwTZB5uWK41t+VfOJaQRf8nb07VbUaqxifwasBy23FQt3KcKnzjmg1G/fcqmzLWBk4c1p1Xc3+MVBhuZ5iJW3aP0YNJN1KPJC1PF63KpCRV1aG6Tzd1Bm+OAYBwhPMKDHJjoXUCE0JKwIfzg9HB991egFa2JT64Eh2RAIzPHOOSREw+cdiHfsUPhH5d5z+I8yvDoon1zWtB16IVAxHlS/glHz2G5Td5Z5LPVpgF88X+yo4UJMJiKPwwsFhk2rob19qq6bshH9b1FFdMrixYFQNe/kkZ/fEJnfAGiRoS/JVCieUOzlB2RjWH865F5iMiFV7wD3nWiyNYG3I4rKAkW/Gs6+DVRX6B8+CPsjHjtfFTPRTx2z7A+WkZsChwFWEAGcpOP/jmWp1v4IuAIl2T7Arna7skRgTBpR69yNdjUT3juaw=
  distributions: sdist bdist_wheel
